name: CITEST
on:
  - push
  - workflow_dispatch

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: "Get list dir"
        run: ls -a
      - name: "Get Memory"
        run: free -h
      - name: "Get Ram"
        run: vmstat -s
      - name: mkdir
        run: mkdir my-test
      - name: "Get list dir"
        run: ls -a

  CloneRepo:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone repo"
        uses: actions/checkout@v6
      - name: "Get list dir"
        run: ls -a
